In [2]:
import pandas  as pd
import numpy as np
import warnings
warnings.filterwarnings('ignore')

In [3]:
analyze = pd.read_csv('REALdata.csv')

In [4]:
analyze = analyze.drop(columns=['Unnamed: 0'])

In [5]:
analyze

planet_name   host_name  orbital_period_[days]  \
0         11 Com b      11 Com             326.030000   
1         11 UMi b      11 UMi             516.219970   
2         14 And b      14 And             185.840000   
3         14 Her b      14 Her            1765.038901   
4       16 Cyg B b    16 Cyg B             798.500000   
...            ...         ...                    ...   
5260  Kepler-228 d  Kepler-228              11.094286   
5261  Kepler-229 b  Kepler-229               6.252972   
5262  Kepler-229 c  Kepler-229              16.068638   
5263  Kepler-229 d  Kepler-229              41.194912   
5264   Kepler-23 b   Kepler-23               7.107300   

      orbit_semi-major_axis_[au])  planet_radius  planet_mass  planet_density  \
0                        1.290000          12.10   6165.60000          19.100   
1                        1.530000          12.30   4684.81420          13.800   
2                        0.830000          12.90   1525.50000           3.900   
3                        2.773069          12.60   2586.74645           7.110   
4                        1.660000          13.50    565.73740           1.260   
...                           ...            ...          ...             ...   
5260                     0.101000           4.04     15.40000           1.280   
5261                     0.062000           2.20      5.48000           2.830   
5262                     0.117000           4.92     21.50000           0.992   
5263                     0.220000           3.85     14.20000           1.370   
5264                     0.075000           1.90    254.30000             NaN   

      eccentricity  equilibrium_temperature_[k]  \
0         0.231000                          NaN   
1         0.080000                          NaN   
2         0.000000                          NaN   
3         0.372689                          NaN   
4         0.680000                          NaN   
...            ...                          ...   
5260      0.000000                        835.0   
5261      0.000000                        823.0   
5262      0.000000                        600.0   
5263      0.000000                        439.0   
5264      0.060000                       1157.0   

      ratio_of_semi-major_axis_to_stellar_radius  \
0                                      14.599543   
1                                      11.043941   
2                                      16.225144   
3                                     641.181348   
4                                     315.887759   
...                                          ...   
5260                                   10.900000   
5261                                   18.940000   
5262                                   36.850000   
5263                                   70.750000   
5264                                   10.643000   

      stellar_effective_temperature_[k]  stellar_radius_[solar_radius]  \
0                                4742.0                          19.00   
1                                4213.0                          29.79   
2                                4813.0                          11.00   
3                                5338.0                           0.93   
4                                5750.0                           1.13   
...                                 ...                            ...   
5260                             6043.0                           1.01   
5261                             5120.0                           0.73   
5262                             5120.0                           0.73   
5263                             5120.0                           0.73   
5264                             5760.0                           1.52   

      stellar_mass_[solar_mass]  distance_[pc]  number_of_planets  \
0                          2.70        93.1846                  1   
1                          2.78       125.3210                  1   
2              

In [5]:
analyze['Datetest'] = analyze['planet_radius'].str[:2]
analyze['datatest2'] = analyze['planet_mass'].str[:2]
analyze['datatest3'] = analyze['equilibrium_temperature_[k]'].str[0]
# crea una variable que guarda las filas que tienen '1' en la columna 'Datetest' y '1' en la columna 'datatest2' como condicion
algo = analyze[(analyze['Datetest'] == '1.') & (analyze['datatest2'] == '1.') & (analyze['datatest3'] == '2')]
print(len(algo))
algo

14


planet_name    host_name orbital_period_[days]  \
174       GJ 1002 b      GJ 1002           10.34650000   
1179    Wolf 1069 b    Wolf 1069           15.56400000   
1398   TRAPPIST-1 f   TRAPPIST-1            9.20754000   
1425      TOI-700 d      TOI-700           37.42396000   
1438      TOI-561 b      TOI-561            0.44657800   
1662  Proxima Cen b  Proxima Cen           11.18680000   
1949   Kepler-929 b   Kepler-929            0.92103214   
2147    Kepler-78 b    Kepler-78            0.35500744   
2158   Kepler-770 c   Kepler-770            1.47532231   
3469   Kepler-438 b   Kepler-438           35.23319000   
4269  Kepler-1288 b  Kepler-1288            2.76122421   
4599  Kepler-1531 b  Kepler-1531            1.13854338   
4674  Kepler-1589 b  Kepler-1589            0.99166527   
4752  Kepler-1649 c  Kepler-1649           19.53527000   

     orbit_semi-major_axis_[au]) planet_radius planet_mass planet_density  \
174                     0.045700         1.030     1.08000       5.430000   
1179                    0.067200         1.080     1.26000       5.500000   
1398                    0.038490         1.045     1.03900       5.022904   
1425                    0.163300         1.073     1.25000       5.560000   
1438                    0.010550         1.423     1.59000       3.000000   
1662                    0.048560         1.030     1.07000       5.380000   
1949                    0.019200         1.110     1.41000       5.670000   
2147                                     1.121     1.96716       5.260000   
2158                    0.030900         1.200     1.87000       5.950000   
3469                    0.166000         1.120     1.46000       5.710000   
4269                    0.043500         1.120     1.46000       5.710000   
4599                    0.022000         1.110     1.41000       5.670000   
4674                    0.020500         1.090     1.32000       5.600000   
4752                    0.064900         1.060     1.20000       5.540000   

     eccentricity equilibrium_temperature_[k]  \
174                                       231   
1179                                      250   
1398     0.010070                         218   
1425     0.042000                         269   
1438     0.000000                        2480   
1662     0.020000                         234   
1949     0.000000                        2362   
2147     0.000000                        2250   
2158     0.000000                        2740   
3469     0.030000                         288   
4269     0.000000                        2017   
4599     0.000000                        2537   
4674     0.000000                        2102   
4752     0.000000                         234   

     ratio_of_semi-major_axis_to_stellar_radius  ...  \
174                                              ...   
1179                                             ...   
1398                                  69.543000  ...   
1425                                  82.900000  ...   
1438                                   2.646000  ...   
1662                                             ...   
1949                                   2.862300  ...   
2147                                   2.660000  ...   
2158                                   4.913000  ...   
3469                                  73.000000  ...   
4269                                   2.560000  ...   
4599                                   4.151000  ...   
4674                                   3.192000  ...   
4752                                  76.800000  ...   

     stellar_mass_[solar_mass] stellar_metallicity_[dex] distance_[pc]  \
174                       0.12                    -0.250     4.8486700   
1179                      0.17                     0.070     9.5834100   
1398                      0.09                     0.040    12.4298888   
1425                      0.42                    -0.070    31.1265000   
1438                      0.79    

In [10]:
analyze['nulltest'] = analyze['planet_name'].str[:12]
algo  = analyze[analyze['nulltest'] == 'TRAPPIST-1 e']
algo

planet_name   host_name  orbital_period_[days]  \
1399  TRAPPIST-1 e  TRAPPIST-1               6.101013   

      orbit_semi-major_axis_[au])  planet_radius  planet_mass  planet_density  \
1399                      0.02925           0.92        0.692        4.901605   

      eccentricity  equilibrium_temperature_[k]  \
1399        0.0051                        250.0   

      ratio_of_semi-major_axis_to_stellar_radius  \
1399                                      52.855   

      stellar_effective_temperature_[k]  stellar_radius_[solar_radius]  \
1399                             2566.0                           0.12   

      stellar_mass_[solar_mass]  distance_[pc]  number_of_planets  \
1399                       0.09      12.429889                  7   

      insolation_flux_earth  stellar_surface_gravity  stellar_age_[gyr]  \
1399                   0.65                     5.24                0.5   

          nulltest  
1399  TRAPPIST-1 e

In [97]:
euclidean = pd.read_csv('FINAL_ML_con_TIERRA.csv')

In [126]:
euclidean[euclidean['Unnamed: 0'] == 1662]

Unnamed: 0    planet_name    host_name  orbital_period_[days]  \
1662        1662  Proxima Cen b  Proxima Cen                11.1868   

      orbit_semi-major_axis_[au])  planet_radius  planet_mass  planet_density  \
1662                      0.04856           1.03         1.07            5.38   

      eccentricity  equilibrium_temperature_[k]  \
1662          0.02                        234.0   

      ratio_of_semi-major_axis_to_stellar_radius  \
1662                                   74.585395   

      stellar_effective_temperature_[k]  stellar_radius_[solar_radius]  \
1662                             2900.0                           0.14   

      stellar_mass_[solar_mass]  distance_[pc]  number_of_planets  \
1662                       0.12        1.30119                  1   

      insolation_flux_earth  stellar_surface_gravity  stellar_age_[gyr]  
1662                   0.65                     5.16           0.366293

In [99]:
euclidean_test = euclidean.drop(columns=['Unnamed: 0', 'planet_name', 'host_name', 'ratio_of_semi-major_axis_to_stellar_radius', 'stellar_effective_temperature_[k]', 'stellar_radius_[solar_radius]', 'stellar_mass_[solar_mass]', 'distance_[pc]', 'number_of_planets', 'stellar_surface_gravity', 'stellar_age_[gyr]'])

In [100]:
euclidean_test.drop('orbital_period_[days]', axis=1, inplace=True)

In [101]:
euclidean_test.drop('orbit_semi-major_axis_[au])', axis=1, inplace=True)

In [103]:
euclidean_test.dropna(inplace=True)

In [102]:
euclidean_test.drop('insolation_flux_earth', axis=1, inplace=True)

In [86]:
euclidean_test = euclidean_test.drop(euclidean_test.index[-1])

In [125]:
euclidean_test.iloc[1582]

planet_radius                    1.03
planet_mass                      1.07
planet_density                   5.38
eccentricity                     0.02
equilibrium_temperature_[k]    234.00
Name: 1662, dtype: float64

In [106]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
standardized_euclidean = scaler.fit_transform(euclidean_test)

In [107]:
standardized_euclidean

array([[3.54431900e-01, 1.34914140e-01, 1.47832895e-02, 5.10437753e-01,
        6.95522821e-02],
       [3.60437185e-01, 1.02511806e-01, 1.06746669e-02, 4.07622872e-01,
        6.95522821e-02],
       [3.78453039e-01, 3.33801623e-02, 3.00006977e-03, 3.53151412e-01,
        6.95522821e-02],
       ...,
       [1.06713908e-01, 3.10120537e-04, 1.03878385e-03, 3.53151412e-01,
        1.00846614e-01],
       [4.81623829e-02, 5.56395302e-03, 2.70878000e-02, 3.94005007e-01,
        2.79631474e-01],
       [2.11386020e-02, 2.12801003e-05, 4.25591293e-03, 3.64522330e-01,
        5.50298805e-02]])

In [46]:
earth = scaler.transform(earth_row.reshape(1, -1))

In [108]:
earth = standardized_euclidean[-1].reshape(1, -1)

In [44]:
earth_row  = standardized_euclidean[-1]

In [109]:
from sklearn.metrics import euclidean_distances
distances = euclidean_distances(standardized_euclidean, earth)

In [110]:
len(distances)

4846

In [111]:
distances[:15]

array([[0.38845018],
       [0.35740396],
       [0.35934412],
       [0.42831165],
       [0.58754626],
       [0.36007986],
       [0.3555434 ],
       [0.64395168],
       [0.38806568],
       [0.37620561],
       [0.43002666],
       [0.46826858],
       [0.48544391],
       [0.4363443 ],
       [0.42945942]])

In [112]:
min(distances)

array([0.])

In [113]:
np.argmin(distances)

4845

In [124]:
for index, v in enumerate(distances):
    if v == sorted_distances[1]:
        print(index)

1582


In [118]:
sorted_distances = np.sort(distances, axis=0)

In [119]:
sorted_distances

array([[0.        ],
       [0.00576327],
       [0.00836267],
       ...,
       [1.12305414],
       [1.154686  ],
       [1.20464144]])